---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-12.04
  - name: ubuntu-14.04
    run_list: test-helper::default
#  - name: ubuntu-12.10
#  - name: centos-6.4


attribute_defaults: &attribute_defaults
  thumbor:
    workers: 3
    install_method: pip

suites:
  - name: default
    run_list: thumbor::default
    attributes:
      thumbor:
        options:
          # ENGINE: graphicsmagick_engine
          ENGINE: thumbor.engines.pil
      <<: *attribute_defaults
  - name: thumbor-engines-opencv
    run_list: thumbor::default
    attributes:
      thumbor:
        <<: *attribute_defaults
        options:
          ENGINE: thumbor.engines.opencv
  - name: thumbor-engines-graphicsmagick
    run_list:
      - recipe[thumbor::default]
    attributes:
      thumbor:
        <<: *attribute_defaults
        options:
          ENGINE: thumbor.engines.graphicsmagick
