---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-12.04
  - name: ubuntu-14.04
    run_list: test-helper::default
#  - name: ubuntu-12.10
  - name: centos-6.5
    run_list: test-helper::default


attribute_defaults: &attribute_defaults
  thumbor:
    workers: 3

suites:
  - name: default
    run_list: thumbor::default
    attributes:
      <<: *attribute_defaults
  - name: thumbor-engines-opencv
    run_list: thumbor::default
    attributes:
      thumbor:
        options:
          ENGINE: opencv_engine
      <<: *attribute_defaults
  - name: thumbor-engines-graphicsmagick
    run_list: thumbor::default
    attributes:
      thumbor:
        options:
          ENGINE: graphicsmagick_engine
      <<: *attribute_defaults
